<?php

// Normal Pages ID
const METODO_PAGE_ID = 9;
const HOME_PAGE_ID = 11;
const NOSOTROS_PAGE_ID = 13;
const SOLUCIONES_PAGE_ID = 15;

// Duraluxe Pages ID
const DURALUXE_HOME_PAGE_ID = 26;
const DURALUXE_ACABADOS_PAGE_ID = 28;
const DURALUXE_ACABADOS_BRILLANTE_PAGE_ID = 30;
const DURALUXE_ACABADOS_CANVAS_PAGE_ID = 33;
const DURALUXE_ACABADOS_CEPILLADO_PAGE_ID = 35;
const DURALUXE_ACABADOS_GLOW_PAGE_ID = 37;
const DURALUXE_ACABADOS_ICETOUCH_PAGE_ID = 39;
const DURALUXE_ACABADOS_MATE_PAGE_ID = 41;
const DURALUXE_ACABADOS_SALTLAKE_PAGE_ID = 43;
const DURALUXE_ACABADOS_SATINADO_PAGE_ID = 45;
const DURALUXE_ACABADOS_WALLSKY_PAGE_ID = 47;
const DURALUXE_CONTACTO_PAGE_ID = 49;
const DURALUXE_HISTORIA_PAGE_ID = 51;
const DURALUXE_MERCADOS_PAGE_ID = 53;
const DURALUXE_MISION_PAGE_ID = 55;
const DURALUXE_PORQUE_PAGE_ID = 57;
const DURALUXE_SOPORTE_PAGE_ID = 60;
const DURALUXE_SOPORTE_CATALOGO_PAGE_ID = 62;


add_filter( 'pages_in_duraluxe_section', 'pages_in_duraluxe_section' );
add_filter( 'pages_in_acabados_section', 'pages_in_acabados_section' );
add_filter( 'pages_in_soporte_section', 'pages_in_soporte_section' );

function pages_in_duraluxe_section( $arg = '' ): array
{
    return [
        DURALUXE_HOME_PAGE_ID,
        DURALUXE_ACABADOS_PAGE_ID,
        DURALUXE_ACABADOS_BRILLANTE_PAGE_ID,
        DURALUXE_ACABADOS_CANVAS_PAGE_ID,
        DURALUXE_ACABADOS_CEPILLADO_PAGE_ID,
        DURALUXE_ACABADOS_GLOW_PAGE_ID,
        DURALUXE_ACABADOS_ICETOUCH_PAGE_ID,
        DURALUXE_ACABADOS_MATE_PAGE_ID,
        DURALUXE_ACABADOS_SALTLAKE_PAGE_ID,
        DURALUXE_ACABADOS_SATINADO_PAGE_ID,
        DURALUXE_ACABADOS_WALLSKY_PAGE_ID,
        DURALUXE_CONTACTO_PAGE_ID,
        DURALUXE_HISTORIA_PAGE_ID,
        DURALUXE_MERCADOS_PAGE_ID,
        DURALUXE_MISION_PAGE_ID,
        DURALUXE_PORQUE_PAGE_ID,
        DURALUXE_SOPORTE_PAGE_ID,
        DURALUXE_SOPORTE_CATALOGO_PAGE_ID,
    ];
}

function pages_in_acabados_section( $arg = '' ): array
{
    return [
        DURALUXE_ACABADOS_PAGE_ID,
        DURALUXE_ACABADOS_BRILLANTE_PAGE_ID,
        DURALUXE_ACABADOS_CANVAS_PAGE_ID,
        DURALUXE_ACABADOS_CEPILLADO_PAGE_ID,
        DURALUXE_ACABADOS_GLOW_PAGE_ID,
        DURALUXE_ACABADOS_ICETOUCH_PAGE_ID,
        DURALUXE_ACABADOS_MATE_PAGE_ID,
        DURALUXE_ACABADOS_SALTLAKE_PAGE_ID,
        DURALUXE_ACABADOS_SATINADO_PAGE_ID,
        DURALUXE_ACABADOS_WALLSKY_PAGE_ID,
    ];
}

function pages_in_soporte_section( $arg = '' ): array
{
    return [
        DURALUXE_SOPORTE_PAGE_ID,
        DURALUXE_SOPORTE_CATALOGO_PAGE_ID,
    ];
}